build:
  image: node:15
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy-dev:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache rsync openssh-client
    - chmod 600 .ssh/id_ecdsa
    - rsync -av --delete-after -e "ssh -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\" -i .ssh/id_ecdsa" dist/ gitlab@10.183.148.183:www/report
