build:
  image: node:15
  stage: build
  variables:
    PUBLIC_PATH: "/report"
    VUE_APP_ID: "ec4b0c0e-f60b-11eb-bb74-50465d7427c0"
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy-dev:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - rsync -rav --delete-after -e "ssh -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"" dist/ gitlab@10.183.148.183:www/report
